apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
  - protocol: {{ .Values.backend.service.protocol }}
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
