apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.deployment.containers.name }}
        image: {{ .Values.frontend.deployment.containers.image.repository }}:{{ .Values.frontend.deployment.containers.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.containers.containerPort }}
        volumeMounts:
        - name: {{ .Values.frontend.deployment.volume.name }}
          mountPath: {{ .Values.frontend.deployment.volume.mountPath }}
          subPath: {{ .Values.frontend.deployment.volume.subPath }}
      imagePullSecrets:
      - name: {{ .Values.docker.secret.name }}
      volumes:
      - name: {{ .Values.frontend.deployment.volume.name }}
        configMap:
          name: {{ .Values.frontend.configMap.name }}
