apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.labels.app }}
  ports:
  - protocol: {{ .Values.frontend.service.protocol }}
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}


