apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  labels:
    app: {{ .Values.mongodb.labels.app }}
spec:
  ports:
    - port: {{ .Values.mongodb.containerPort }}
      name: {{ .Values.mongodb.portName }}
  clusterIP: None
  selector:
    app: {{ .Values.mongodb.labels.app }}

